#!/bin/sh
config_libvirt_netbps() {
  cat <<-_EOF_
	graph_title VM Net Usage
	graph_args --base 1000
	graph_vlabel bits in (-) / out (+) per \${graph_period}
	graph_category virtualization
	graph_info This graph shows the traffic generated/consumed by a VM.
	graph_period second
	_EOF_
  for vmid in $(virsh list --uuid)
  do
    vmname=$(virsh domname "$vmid")
    vmlabel=v$(echo $vmname | tr -sc A-Za-z0-9 _)
    cat <<-_EOF_
	down_$vmlabel.label $vmname received
	down_$vmlabel.type DERIVE
	down_$vmlabel.min 0
	down_$vmlabel.graph no
	up_$vmlabel.label $vmname bps
	up_$vmlabel.type DERIVE
	up_$vmlabel.min 0
	up_$vmlabel.negative down_$vmlabel
	_EOF_
  done
}
fetch_libvirt_netbps() {
  for vmid in $(virsh list --uuid)
  do
    vmlabel=v$(virsh domname "$vmid"| tr -sc A-Za-z0-9 _)
    virsh domstats $vmid | awk -vFS="=" '
	$1 ~ /net.*rx.bytes$/ { rx_bytes += $2 }
	$1 ~ /net.*tx.bytes$/ { tx_bytes += $2 }
	END {
	  print "down_'"$vmlabel"'.value",rx_bytes*8
	  print "up_'"$vmlabel"'.value",tx_bytes*8
	}
    '
  done
}
