#!/bin/sh
config_libvirt_blkiops() {
  cat <<-_EOF_
	graph_title VM IOPs
	graph_args --base 1000
	graph_vlabel iops read (-) / write (+) per \${graph_period}
	graph_category virtualization
	graph_info This graph shows the IOPs (I/O Operations) generated/consumed by a VM.
	graph_period second
	_EOF_
  for vmid in $(virsh list --uuid)
  do
    vmname=$(virsh domname "$vmid")
    vmlabel=v$(echo $vmname | tr -sc A-Za-z0-9 _)
    cat <<-_EOF_
	down_$vmlabel.label $vmname read
	down_$vmlabel.type DERIVE
	down_$vmlabel.min 0
	down_$vmlabel.graph no
	up_$vmlabel.label $vmname iops
	up_$vmlabel.type DERIVE
	up_$vmlabel.min 0
	up_$vmlabel.negative down_$vmlabel
	_EOF_
  done
}
fetch_libvirt_blkiops() {
  for vmid in $(virsh list --uuid)
  do
    vmlabel=v$(virsh domname "$vmid"| tr -sc A-Za-z0-9 _)
    virsh domstats $vmid | awk -vFS="=" '
	$1 ~ /block.*rd.reqs$/ { down_cnt += $2 }
	$1 ~ /block.*wr.reqs$/ { up_cnt += $2 }
	END {
	  print "down_'"$vmlabel"'.value",down_cnt
	  print "up_'"$vmlabel"'.value",up_cnt
	}
    '
  done
}
