#!/bin/sh

config_uptime() {
  echo "graph_title Uptime"
  echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit 110"
  echo "graph_vlabel uptime %"
  echo "graph_scale no"
  echo "graph_category system"
  echo "graph_period second"

  echo "uptime.label uptime"
  echo "uptime.draw AREA"
  echo "uptime.type DERIVE"
  echo "uptime.min 0"
}
fetch_uptime() {
  echo "uptime.value" $(awk '{printf "%d",$1*100}' /proc/uptime)
}

#~ config_uptime() {
  #~ echo "graph_title Uptime"
  #~ echo "graph_args --base 1000 -l 0 "
  #~ echo "graph_vlabel uptime in days"
  #~ echo "uptime.label uptime"
  #~ echo "uptime.draw AREA"
  #~ echo "uptime.cdef uptime,86400,/"
#~ }
